# Generated by Django 5.1.6 on 2025-02-18 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='country_name',
            field=models.CharField(default='---', max_length=100),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='mobile_number',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.RegexValidator(message='⚠️ Mobile number must be a Valid number⚠️', regex='^\\d{10}$')]),
        ),
    ]
