# Generated by Django 5.1.6 on 2025-02-18 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactmessage_country_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='country_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='mobile_number',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.RegexValidator(message='⚠️ Mobile number must be a Valid number⚠️', regex='^\\d{10}$')]),
        ),
    ]
