# Generated by Django 5.1.6 on 2025-02-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contactmessage_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='services',
            field=models.CharField(choices=[('web_design', 'Web Designing & Development'), ('graphic_design', 'Graphic Designing (Logo, Banner, Posters)'), ('seo', 'SEO Optimization & Digital Marketing'), ('social_media', 'Social Media Management'), ('branding', 'Branding & Business Identity')], default='', help_text='Select one or more services you are interested in.', max_length=255),
        ),
    ]
