# Generated by Django 5.1.6 on 2025-02-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactmessage_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='services',
            field=models.JSONField(default=list),
        ),
    ]
