# Generated by Django 5.1.6 on 2025-03-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_careerapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerapplication',
            name='resume',
        ),
    ]
